// import product1 from "@/assets/products/Rectangle 8 (12).png"
// import product2 from "@/assets/products/Rectangle 8 (13).png"
// import product3 from "@/assets/products/Rectangle 8 (14).png"
// import product4 from "@/assets/products/Rectangle 8 (16).png"
// import product5 from "@/assets/products/Rectangle 8 (17).png"
// import product6 from "@/assets/products/Rectangle 10.png"

// export const products = [
//   {
//     id: "1",
//     name: "Braised Beef Noodles",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Meats",
//     image: product1,
//     rating: 4.5,
//     unit: "1 pack",
//     featured: true,
//     stockOffer: true,
//     newStock: false,
//     popular: false,
//     brand: "Local Farm",
//     country: "Japan",
//     janCode: "4901234567890",
//   },
//   {
//     id: "2",
//     name: "Premium Frozen Meats",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Frozen meat's",
//     image: product2,
//     rating: 4.5,
//     unit: "1 pack",
//     featured: true,
//     stockOffer: false,
//     newStock: true,
//     popular: false,
//     brand: "Premium Meats",
//     country: "USA",
//     janCode: "4901234567891",
//   },
//   {
//     id: "3",
//     name: "Beef whole",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Frozen food's",
//     image: product3,
//     rating: 4.5,
//     unit: "1 kg",
//     featured: true,
//     stockOffer: true,
//     newStock: false,
//     popular: false,
//     brand: "Local Farm",
//     country: "Australia",
//     janCode: "4901234567892",
//   },
//   {
//     id: "4",
//     name: "Instant Ramen Bowls",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Ramen",
//     image: product4,
//     rating: 4.5,
//     unit: "1 pack",
//     featured: true,
//     stockOffer: false,
//     newStock: true,
//     popular: true,
//     brand: "Nissin",
//     country: "Japan",
//     janCode: "4901234567893",
//   },
//   {
//     id: "5",
//     name: "Cold-Pressed Juices",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Juices",
//     image: product5,
//     rating: 4.5,
//     unit: "1 pack",
//     featured: true,
//     stockOffer: true,
//     newStock: false,
//     popular: false,
//     brand: "Fresh Squeeze",
//     country: "USA",
//     janCode: "4901234567894",
//   },
//   {
//     id: "6",
//     name: "Zasai whole",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Preserved Foods",
//     image: product6,
//     rating: 4.5,
//     unit: "1 kg",
//     featured: true,
//     stockOffer: false,
//     newStock: true,
//     popular: false,
//     brand: "Traditional",
//     country: "China",
//     janCode: "4901234567895",
//   },
//   {
//     id: "7",
//     name: "Crunchy Nuts & Snacks",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Nuts",
//     image: product1,
//     rating: 4.5,
//     unit: "1 pack",
//     featured: true,
//     stockOffer: true,
//     newStock: false,
//     popular: false,
//     brand: "Nutty Delights",
//     country: "Turkey",
//     janCode: "4901234567896",
//   },
//   {
//     id: "8",
//     name: "Fresh & Dried Fruits",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Meats",
//     image: product1,
//     rating: 4.5,
//     unit: "1 pack",
//     featured: true,
//     stockOffer: false,
//     newStock: true,
//     popular: false,
//     brand: "Fruit Farm",
//     country: "Thailand",
//     janCode: "4901234567897",
//   },
//   {
//     id: "9",
//     name: "Brown coffee",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Food's",
//     image: product1,
//     rating: 4.5,
//     unit: "1 kg",
//     featured: false,
//     stockOffer: true,
//     newStock: false,
//     popular: false,
//     brand: "Coffee Co.",
//     country: "Brazil",
//     janCode: "4901234567898",
//     onSale: true,
//   },
//   {
//     id: "10",
//     name: "PolarPeach Slices",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Food's",
//     image: product1,
//     rating: 4.5,
//     unit: "1 kg",
//     featured: false,
//     stockOffer: false,
//     newStock: true,
//     popular: false,
//     brand: "Polar Foods",
//     country: "Chile",
//     janCode: "4901234567899",
//   },
//   {
//     id: "11",
//     name: "Frozen ground meat",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Frozen meats",
//     image: product1,
//     rating: 4.5,
//     unit: "1 pack",
//     featured: false,
//     stockOffer: true,
//     newStock: true,
//     popular: false,
//     brand: "Meat Masters",
//     country: "USA",
//     janCode: "4901234567900",
//   },
//   {
//     id: "12",
//     name: "Nissin RAOH Ramen",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Ramen",
//     image: product1,
//     rating: 4.5,
//     unit: "1 pack",
//     featured: false,
//     stockOffer: false,
//     newStock: true,
//     popular: false,
//     brand: "Nissin",
//     country: "Japan",
//     janCode: "4901234567901",
//   },
//   {
//     id: "13",
//     name: "Angus Beef",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Beef",
//     image: product1,
//     rating: 4.5,
//     unit: "1 kg",
//     featured: false,
//     stockOffer: true,
//     newStock: true,
//     popular: false,
//     brand: "Premium Meats",
//     country: "Australia",
//     janCode: "4901234567902",
//   },
//   {
//     id: "14",
//     name: "Tanajari",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Coffee",
//     image: product1,
//     rating: 4.5,
//     unit: "1 pack",
//     featured: false,
//     stockOffer: false,
//     newStock: true,
//     popular: true,
//     brand: "Coffee Co.",
//     country: "Ethiopia",
//     janCode: "4901234567903",
//   },
//   {
//     id: "15",
//     name: "Clam Chowder Pasta - Knorr",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Soup",
//     image: product1,
//     rating: 4.5,
//     unit: "1 pack",
//     featured: false,
//     stockOffer: true,
//     newStock: false,
//     popular: true,
//     brand: "Knorr",
//     country: "USA",
//     janCode: "4901234567904",
//   },
//   {
//     id: "16",
//     name: "Craft Beer",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Beer",
//     image: product1,
//     rating: 4.5,
//     unit: "1 pack",
//     featured: false,
//     stockOffer: false,
//     newStock: true,
//     popular: true,
//     brand: "Craft Brewery",
//     country: "Germany",
//     janCode: "4901234567905",
//   },
//   {
//     id: "17",
//     name: "Fresh-Catch Frozen Fish",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Frozen fish",
//     image: product1,
//     rating: 4.5,
//     unit: "1 kg",
//     featured: false,
//     stockOffer: true,
//     newStock: false,
//     popular: true,
//     brand: "Ocean Fresh",
//     country: "Norway",
//     janCode: "4901234567906",
//   },
//   {
//     id: "18",
//     name: "Beef whole",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Frozen food's",
//     image: product3,
//     rating: 4.5,
//     unit: "1 kg",
//     featured: true,
//     stockOffer: true,
//     newStock: false,
//     popular: false,
//     brand: "Local Farm",
//     country: "Australia",
//     janCode: "4901234567892",
//   },
//   {
//     id: "19",
//     name: "Beef whole",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Frozen food's",
//     image: product3,
//     rating: 4.5,
//     unit: "1 kg",
//     featured: true,
//     stockOffer: true,
//     newStock: false,
//     popular: false,
//     brand: "Local Farm",
//     country: "Australia",
//     janCode: "4901234567892",
//   },
//   {
//     id: "20",
//     name: "Beef whole",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Frozen food's",
//     image: product3,
//     rating: 4.5,
//     unit: "1 kg",
//     featured: true,
//     stockOffer: true,
//     newStock: false,
//     popular: false,
//     brand: "Local Farm",
//     country: "Australia",
//     janCode: "4901234567892",
//   },
//   {
//     id: "21",
//     name: "Beef whole",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Frozen food's",
//     image: product3,
//     rating: 4.5,
//     unit: "1 kg",
//     featured: true,
//     stockOffer: true,
//     newStock: false,
//     popular: false,
//     brand: "Local Farm",
//     country: "Australia",
//     janCode: "4901234567892",
//   },
//   {
//     id: "22",
//     name: "Beef whole",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Frozen food's",
//     image: product3,
//     rating: 4.5,
//     unit: "1 kg",
//     featured: true,
//     stockOffer: true,
//     newStock: false,
//     popular: false,
//     brand: "Local Farm",
//     country: "Australia",
//     janCode: "4901234567892",
//   },
//   {
//     id: "23",
//     name: "Beef whole",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Frozen food's",
//     image: product3,
//     rating: 4.5,
//     unit: "1 kg",
//     featured: true,
//     stockOffer: true,
//     newStock: false,
//     popular: false,
//     brand: "Local Farm",
//     country: "Australia",
//     janCode: "4901234567892",
//   },
//   {
//     id: "24",
//     name: "Beef whole",
//     description: "Rich in vitamin C and antioxidants for a healthy boost.",
//     price: 20.0,
//     category: "Frozen food's",
//     image: product3,
//     rating: 4.5,
//     unit: "1 kg",
//     featured: true,
//     stockOffer: true,
//     newStock: false,
//     popular: false,
//     brand: "Local Farm",
//     country: "Australia",
//     janCode: "4901234567892",
//   },
// ]

// export const categories = [
//   "Meats",
//   "Frozen meat's",
//   "Frozen food's",
//   "Frozen fish",
//   "Ramen",
//   "Juices",
//   "Tea & Beverages",
//   "Nuts",
//   "Noodles",
//   "Beer",
//   "Beans",
//   "Processed Foods",
//   "Flour",
//   "Dried & Fresh Fruit",
//   "Lentils",
//   "Soups",
//   "Preserved Foods",
//   "Coffee",
//   "Food's",
//   "Beef",
//   "Soup",
// ]

// export const brands = [
//   "Local Farm",
//   "Premium Meats",
//   "Nissin",
//   "Fresh Squeeze",
//   "Traditional",
//   "Nutty Delights",
//   "Fruit Farm",
//   "Coffee Co.",
//   "Polar Foods",
//   "Meat Masters",
//   "Knorr",
//   "Craft Brewery",
//   "Ocean Fresh",
// ]

// export const countries = [
//   "Japan",
//   "USA",
//   "Australia",
//   "China",
//   "Turkey",
//   "Thailand",
//   "Brazil",
//   "Chile",
//   "Ethiopia",
//   "Germany",
//   "Norway",
// ]
